# Generated by Django 5.0.1 on 2024-02-23 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0002_author_category_course_delete_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='video_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
