# Generated by Django 5.0.1 on 2024-05-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0009_alter_productreview_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Disabled', 'Disabled'), ('Rejected', 'Rejected'), ('In_review', 'In_review'), ('Published', 'Published')], default=None, max_length=700, null=True),
        ),
    ]
